name: NAStool Package
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - version.py
      - .github/workflows/build-package.yml
      - requirements.txt

jobs:
  Windows-build:
    runs-on: windows-latest
    steps:
    - name: Init Python 3.10.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.10'

    - name: Checkout
      uses: actions/checkout@master

    - name: Install dependent packages
      run: |
        python -m pip install --upgrade pip
        pip install wheel numpy==1.23.5 pyparsing==3.0.9 wxpython==4.2.0 pyinstaller==5.7.0
        pip install -r requirements.txt
        echo ("NASTOOL_CONFIG=D:/a/nas-tools-dev/nas-tools-dev/nas-tools-dev/config/config.yaml") >> $env:GITHUB_ENV
        echo $env:NASTOOL_CONFIG
        cd third_party
        git submodule init
        git submodule update
      shell: pwsh

    - name: Package through pyinstaller
      run: |
        dir
        copy .\package\rely\upx.exe c:\hostedtoolcache\windows\python\3.10.10\x64\Scripts
        copy .\package\rely\hook-cn2an.py c:\hostedtoolcache\windows\python\3.10.10\x64\lib\site-packages\pyinstaller\hooks
        copy .\package\rely\hook-zhconv.py c:\hostedtoolcache\windows\python\3.10.10\x64\lib\site-packages\pyinstaller\hooks
        copy .\package\rely\hook-iso639.py c:\hostedtoolcache\windows\python\3.10.10\x64\lib\site-packages\pyinstaller\hooks
        copy .\third_party.txt .\package
        copy .\package\rely\template.jinja2 c:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\setuptools\_vendor\pyparsing\diagram
        xcopy .\web c:\hostedtoolcache\windows\python\3.10.10\x64\lib\site-packages\web\ /e
        xcopy .\config c:\hostedtoolcache\windows\python\3.10.10\x64\lib\site-packages\config\ /e
        xcopy .\scripts c:\hostedtoolcache\windows\python\3.10.10\x64\lib\site-packages\scripts\ /e
        cd package
        pyinstaller nas-tools.spec
        dir
      shell: pwsh

    - name: Upload windows file
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: ./package/dist/nas-tools.exe

  Linux-build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Init Python 3.10.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.10'

    - name: Checkout
      uses: actions/checkout@master

      - name: Install dependent packages
        run: |
          python -m pip install --upgrade pip
          pip install wheel pyinstaller==5.7.0
          pip install -r requirements.txt
          echo ("NASTOOL_CONFIG=/home/runner/work/nas-tools-unlock/nas-tools-unlock/nas-tools-unlock/config/config.yaml") >> $env:GITHUB_ENV
          echo $env:NASTOOL_CONFIG
          cd third_party
          git submodule init
          git submodule update
        shell: pwsh

      - name: Package through pyinstaller
        run: |
          pwd
          ls -all
          cp ./package/rely/hook-cn2an.py /opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/PyInstaller/hooks/
          cp ./package/rely/hook-zhconv.py /opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/PyInstaller/hooks/
          cp ./package/rely/hook-iso639.py /opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/PyInstaller/hooks/
          cp ./third_party.txt ./package/
          cp ./package/rely/template.jinja2 /opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/setuptools/_vendor/pyparsing/diagram/
          cp -r ./web/. /opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/web/
          cp -r ./config/. /opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/config/
          cp -r ./scripts/. /opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/scripts/
          cd package
          pwd
          ls -all
          pyinstaller nas-tools.spec
          mv /home/runner/work/nas-tools-unlock/nas-tools-unlock/nas-tools-unlock/package/dist/nas-tools /home/runner/work/nas-tools-unlock/nas-tools-unlock/nas-tools-unlock/package/dist/nas-tools-unlock.linux.amd64
          ls -all /home/runner/work/nas-tools-unlock/nas-tools-unlock/nas-tools-unlock/package/dist
        shell: pwsh

      - name: Upload linux file
        uses: actions/upload-artifact@v3
        with:
          name: linux-amd64
          path: /home/runner/work/nas-tools-unlock/nas-tools-unlock/nas-tools-unlock/package/dist/nas-tools-unlock.linux.amd64
